language: python

python:
  - "3.5"

sudo: false

# command to install dependencies
install: 
  - "pip install -r requirements.txt"

before_script:

# command to run tests
script: 
  - "nosetests"

notifications:
  slack:
    recipients:
      - @wfqethan
    on_success: always
    on_failure: change
  email:
    recipients:
      - wfqethan@uw.edu
    on_success: always
    on_failure: never