language: python

python:
  - "3.5"

sudo: false

# command to install dependencies
install: 
  - "pip install -r requirements.txt"

before_script:

# command to run tests
script: 
  - "nosetests"

after_script:
  - "coverage report"
  - "coveralls"